### ISSUE TITLE
cargo-maelstrom blocks forever sometimes when there is a build failure

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#205]
cargo test seems to be hung

**Comment by bobbobbio** [comment]
I haven't run into this, but maybe what is happening is that the pipe for stderr is filling up and then it gets stuck in the way you theorized.

I changed it to read stderr on some thread in 4f3598754a26529d4cbc898d5acd92b124aae417, so maybe that has fixed it

**Comment by nfachan** [comment]
I'll close for now and open a new issue if it comes up again.
