### ISSUE TITLE
Re-enable integration tests for clients.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#213]
I broke these when I added the local worker.

**Comment by bobbobbio** [comment]
I've restored all the tests that were deleted. I restored them not as integration tests though. In addition I did add some integration tests of the client library.

I have yet to add any integration tests of cargo-maelstrom though. I think there should be a different issue for that

**Comment by bobbobbio** [comment]
okay I added some cargo-maelstrom integration tests also actually
