### ISSUE TITLE
local worker `--inline-limit` option is blocking `--include` cargo maelstrom option

### ISSUE THREAD

**Issue by bobbobbio** [maelstrom-software/maelstrom#220]
Both `--inline-limit` and `--include` have the same short flag `-i`

**Comment by nfachan** [comment]
Fixed in [63c0a1a4c7e2772a5637641ba7df0902322d0f97](https://github.com/maelstrom-software/maelstrom/commit/63c0a1a4c7e2772a5637641ba7df0902322d0f97)
