### ISSUE TITLE
We should provide the `include_shared_libraries` to the general client and `maelstrom-run`

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#231]
Maybe this would just be a layer type, where you specify some binaries and it then includes all of the shared libraries used by those. So you could do something like `maelstrom-run some-local-program arg1 arg2`, and it would just copy `some-local-program` and any shared libraries into the container, and run it.

**Comment by bobbobbio** [comment]
I think this will be fulfilled by #266

**Comment by bobbobbio** [comment]
This works now, you can use "shared-library-dependencies" layers
