### ISSUE TITLE
Support container registries other than Docker Hub

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#247]
There is currently no way to specify a container image hosted on a registry other than Docker Hub.

We could do like Kubernetes and just look for things that look like hostnames and optional ports: https://kubernetes.io/docs/concepts/containers/images/#image-names . So you'd have something like my.registry.com/image .

Or, we could take an approach like skopeo does: https://github.com/containers/skopeo/blob/main/docs/skopeo.1.md#image-names

I prefer the latter approach, as I imagine we could support other formats in the future.

**Comment by bobbobbio** [comment]
I'm going to call this issue done now. We now work with other container repositories. There are some other things to do in this space that I will create other issues for
