### ISSUE TITLE
We should come up with a better solution for logging in the client process.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#249]
It's unfortunate to just plop down a log file for the client in the target directory (for `cargo-maelstrom`). It seems like we should just use RPCs to send these messages back to the client library.

**Comment by nfachan** [comment]
@bobbobbio what do you think? Is this addressed now?

**Comment by bobbobbio** [comment]
yeah, the thing this talks about is done. There are probably other improvements to be made though.
