### ISSUE TITLE
Add layer type or types for shared-library dependencies.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#266]
If we get this right, we could remove the `include_shared_libraries` field.

We should at least support:
  * The ability to add shared library dependencies for the test binary.
  * The ability to add an arbitrary binary and its shared library dependencies.

**Comment by nfachan** [comment]
Maybe obviate #232

**Comment by bobbobbio** [comment]
We talked about what more specific to do here yesterday. This is what it sounded like we were converging on to me for this issue (and this release)

- Don't mess with the `include_shared_libraries` flag, leave that working how it is
- Add a new layer type which is for the shared library closure of a binary. This doesn't include the binary itself, so you can have separate prefix options for the binary and its dependencies. The binary would have to be included in its own layer.
