### ISSUE TITLE
Fix formatting of remote errors from add_job

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#293]
neal-H270M-DS3H:~/maelstrom(1)[148]% maelstrom-run < ~/run.json
remote error: status: Unknown, message: "get_container_image at /home/neal/maelstrom/crates/maelstrom-container/src/lib.rs:681:22\n\nCaused by:\n    0: get_image_digest at /home/neal/maelstrom/crates/maelstrom-container/src/lib.rs:596:26\n    1: resolve_tag at /home/neal/maelstrom/crates/maelstrom-container/src/lib.rs:398:17\n    2: could not access \"alpine/socat:latest\", are you sure it exists?", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 23 May 2024 16:25:59 GMT", "content-length": "0"} }

**Comment by bobbobbio** [comment]
This is due to add_job not using error mapping code the rest of the client uses
