### ISSUE TITLE
The worker seems to be eating panics

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#304]
We had an issue where the worker got a panic because of an issue with sending the fuse fd over the unix-domain socket. But the worker didn't terminate like it should.

**Comment by nfachan** [comment]
Some more examples:
May 31 17:19:23.100 ERRO Got error servicing FUSE request. Returning EIO, error: DirectoryDataReader::new at /home/neal/maelstrom/crates/maelstrom-layer-fs/src/dir.rs:32:20

Caused by:
    0: open("/home/neal/.cache/maelstrom/worker/artifacts/upper_fs_layer/sha256/2ac7374a3cf84bfdff257722a3192c430ca5c4101f344585b9ed329e067d3197/61.dir_data.bin")
    1: Too many open files (os error 24), spec: JobSpec { program: "/maelstrom_client_process-64c46e52a3fd4061", arguments: ["--exact", "--nocapture", "router::tests::get_job_state_counts_clustered"], environment: ["RUST_BACKTRACE=0"], layers: NonEmpty {
 head: (Sha256Digest(25e448ca4991321ca4260974afc1c74f0778af673a502c72fa1f78ceeb1050af), Manifest), tail: [(Sha256Digest(fc931ec755a8f535c88c902211025a30e102d59aca99e371ef6a445d76f17025), Manifest), (Sha256Digest(7c04db5f7d66001311eb9cbfa1c4cc8fe8860acea8
abc23ab935dfec5d6020e1), Manifest)] }, devices: EnumSet(), mounts: [Tmp { mount_point: "/tmp" }], network: Disabled, root_overlay: None, working_directory: "/", user: UserId(0), group: GroupId(0), timeout: None, estimated_duration: Some(51.28031ms) }, ji
d: JobId { cid: ClientId(15), cjid: ClientJobId(545) }
May 31 17:19:23.289 ERRO Got error servicing FUSE request. Returning EIO, error: DirectoryDataReader::new at /home/neal/maelstrom/crates/maelstrom-layer-fs/src/dir.rs:32:20

Caused by:
    0: open("/home/neal/.cache/maelstrom/worker/artifacts/upper_fs_layer/sha256/2ac7374a3cf84bfdff257722a3192c430ca5c4101f344585b9ed329e067d3197/61.dir_data.bin")
    1: Too many open files (os error 24), spec: JobSpec { program: "/maelstrom_client_process-64c46e52a3fd4061", arguments: ["--exact", "--nocapture", "router::tests::job_response_from_local_worker_unknown_clustered"], environment: ["RUST_BACKTRACE=0"],
layers: NonEmpty { head: (Sha256Digest(25e448ca4991321ca4260974afc1c74f0778af673a502c72fa1f78ceeb1050af), Manifest), tail: [(Sha256Digest(fc931ec755a8f535c88c902211025a30e102d59aca99e371ef6a445d76f17025), Manifest), (Sha256Digest(7c04db5f7d66001311eb9cbf
a1c4cc8fe8860acea8abc23ab935dfec5d6020e1), Manifest)] }, devices: EnumSet(), mounts: [Tmp { mount_point: "/tmp" }], network: Disabled, root_overlay: None, working_directory: "/", user: UserId(0), group: GroupId(0), timeout: None, estimated_duration: Some
(48.562171ms) }, jid: JobId { cid: ClientId(15), cjid: ClientJobId(554) }
May 31 17:19:23.290 ERRO Failed to get pipe memory, cannot splice, error: Os { code: 24, kind: Uncategorized, message: "Too many open files" }, spec: JobSpec { program: "/maelstrom_client_process-64c46e52a3fd4061", arguments: ["--exact", "--nocapture", "
client::state_machine::tests::active_watcher_wait_fail_during_wait"], environment: ["RUST_BACKTRACE=0"], layers: NonEmpty { head: (Sha256Digest(25e448ca4991321ca4260974afc1c74f0778af673a502c72fa1f78ceeb1050af), Manifest), tail: [(Sha256Digest(fc931ec755a
8f535c88c902211025a30e102d59aca99e371ef6a445d76f17025), Manifest), (Sha256Digest(7c04db5f7d66001311eb9cbfa1c4cc8fe8860acea8abc23ab935dfec5d6020e1), Manifest)] }, devices: EnumSet(), mounts: [Tmp { mount_point: "/tmp" }], network: Disabled, root_overlay:
None, working_directory: "/", user: UserId(0), group: GroupId(0), timeout: None, estimated_duration: Some(42.002302ms) }, jid: JobId { cid: ClientId(15), cjid: ClientJobId(521) }
May 31 17:19:41.292 ERRO Failed to get pipe memory, cannot splice, error: Os { code: 24, kind: Uncategorized, message: "Too many open files" }, spec: JobSpec { program: "/maelstrom_pytest-de9ecddbd9fcd167", arguments: ["--exact", "--nocapture", "pattern:
:interpreter::simple_expression_compound_selector_packge"], environment: ["RUST_BACKTRACE=0"], layers: NonEmpty { head: (Sha256Digest(35253475ba0bc0fa54d25d066ca8c1d09ebcabf93da192d609b5bc236c61f28a), Manifest), tail: [(Sha256Digest(7c04db5f7d66001311eb9
cbfa1c4cc8fe8860acea8abc23ab935dfec5d6020e1), Manifest)] }, devices: EnumSet(), mounts: [], network: Disabled, root_overlay: None, working_directory: "/", user: UserId(0), group: GroupId(0), timeout: None, estimated_duration: Some(25.027301ms) }, jid: Jo
bId { cid: ClientId(15), cjid: ClientJobId(581) }
May 31 17:19:41.296 ERRO Got error servicing FUSE request. Returning EIO, error: LayerFs::dir_data_path at /home/neal/maelstrom/crates/maelstrom-layer-fs/src/lib.rs:251:23

Caused by:
    0: LayerFs::root at /home/neal/maelstrom/crates/maelstrom-layer-fs/src/lib.rs:233:25
    1: LayerFs::layer_super at /home/neal/maelstrom/crates/maelstrom-layer-fs/src/lib.rs:268:12
    2: open("/home/neal/.cache/maelstrom/worker/artifacts/upper_fs_layer/sha256/a76e2141bb5434b94319e08d1b482561c03dfa99c22606ac8bad5905ca328165/super.bin")
    3: Too many open files (os error 24), spec: JobSpec { program: "/maelstrom_pytest-de9ecddbd9fcd167", arguments: ["--exact", "--nocapture", "pattern::parser::pattern_complicated_boolean_expr_compound"], environment: ["RUST_BACKTRACE=0"], layers: NonEm
pty { head: (Sha256Digest(35253475ba0bc0fa54d25d066ca8c1d09ebcabf93da192d609b5bc236c61f28a), Manifest), tail: [(Sha256Digest(7c04db5f7d66001311eb9cbfa1c4cc8fe8860acea8abc23ab935dfec5d6020e1), Manifest)] }, devices: EnumSet(), mounts: [], network: Disable
d, root_overlay: None, working_directory: "/", user: UserId(0), group: GroupId(0), timeout: None, estimated_duration: Some(36.656904ms) }, jid: JobId { cid: ClientId(15), cjid: ClientJobId(585) }

**Comment by bobbobbio** [comment]
Did you mean to post that on this bug? That seems like the too many files error and not a panic

**Comment by bobbobbio** [comment]
It doesn't seem to be eating panics anymore from what I can tell. Maybe it was before, but it isn't now. 

The original weirdness I remember had to do with an executor thread panic'ing because it was reading from a future which was sending it stdout.

At the time we were unsure how that was possible because there was no path where the future was cancelled, but now I know that there was a way for the future to be cancelled, and it was jut for the dispatcher to exit due to some error and this causes the tokio runtime to be destroyed and any running futures to be cancelled. The executor thread would then panic.

**Comment by bobbobbio** [comment]
I think there is a high chance this is fixed from either the clean shutdown work or fixes around file descriptor stuff
