### ISSUE TITLE
Local networking and sys filesystem can't coexist

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#310]

**Comment by nfachan** [comment]
See #389

**Comment by bobbobbio** [comment]
I'm not sure what documentation was expected to be added here, we already mention this in this section it seems 
https://maelstrom-software.com/doc/book/latest/spec.html#network

**Comment by bobbobbio** [comment]
The documentation does mention this, so I'm just going to close. We can re-open if there is something missing.
