### ISSUE TITLE
Figure out what pass-through command-line options `maelstrom-pytest` should have.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#320]
Like #319 , but for `pytest`.

**Definition of Done**
- [ ] `CHANGELOG.md` updated.
- [ ] Documentation in `doc/book/head` updated.
- [ ] Issue is in the correct milestone.

**Comment by zed** [comment]
Could arbitrary `pytest` options be accepted e.g. like so: `maelstrom-pytest [maelstrom-options] -- [pass-through-pytest-options]`

There are pytest plugins that introduce their own options e.g., [`pytest-reserial`](https://pypi.org/project/pytest-reserial/) introduces `--record`, `--replay`:

```shell
maelstrom-pytest -- --replay
```

**Comment by nfachan** [comment]
I think your suggestion might be the way to go. One issue I think we have with pytest as opposed to other test runners is that pytest has plugins that may have their own options. This makes it impossible to enumerate all of the pytest options and create maelstrom-pytest options for them.

As a compromise, we could enumerate the base pytest options and create maelstrom-pytest options for them, but then have a way like suggested (`--`) to pass additional options.

**Comment by bobbobbio** [comment]
I agree that we need a backdoor like this in this case. Here are some things to consider.

We actually invoke `pytest` in two different times, once when listing the tests, and another time when actually running a test. Without knowing the meaning of the options we won't know at what time we should pass them, so maybe we a way to specify.

I know `pytest` will also let you specify CLI options via configuration file, and I'm not sure how that may or may not interact with this, we should be aware of that.

Also, in general letting people pass options like this could potentially break our interaction with `pytest` but this is just a reality of allowing this, perhaps we just need to make this clear when documenting this.

**Comment by zed** [comment]
As a workaround `PYTEST_ADDOPTS` envvar could be used to pass through arbitrary pytests' options:

```shell
PYTEST_ADDOPTS=<pass-through-pytest-options> maelstrom-pytest
```
It requires updating `maelstrom-pytest.toml` e.g.:

```toml
added_environment = { PYTEST_ADDOPTS = "$env{PYTEST_ADDOPTS}" }
```

`pytest` configuration can be specified in a file e.g., `pyproject.toml`:

```toml
[tool.pytest.ini_options]
testpaths = ["unit-tests"]
``` 

It is necessary to update `maelstrom-pytest.toml`, to make `pyproject.toml` available:
```toml
added_layers = [
    { glob = "**.py" },
    { paths = [ 
              "pyproject.toml", 
      ] },
] 
```

**Comment by nfachan** [comment]
@zed Thank you for documenting the work-arounds.

I think I'm going to add two new issues for proposed features. The first is as you suggested, to add support for passing `--`, where everything after that will be passed to the individual test binary.

However, this won't work for options passed to the collect phase. I'll add another issue for that.

Finally, it looks like I should add an issue about having pyproject.toml being passed along for the default configuration for pytest.

**Comment by bobbobbio** [comment]
I've gone over all the CLI flags and created issues where I thought appropriate

I'm going to show my work here.

legend for decision column
- replace - support the feature via some other mechanism
- support - somehow support enabling this feature directly
- ignore - just ignore this feature

| CLI option                      | description                      | decision | rationale/issue                           |
| ---                             | ---                              | ---      | ---                                       |
| -k                              | filter test based on expression  | replace  | supported via DSL                         |
| -m                              | filter test based on marker      | replace  | supported via DSL                         |
| --markers                       | show markers                     | support  | issue #395                                |
| --exitfirst                     | exit after first failure         | replace  | supported via `stop-after`                |
| --fixtures                      | show fixtures                    | support  | issue #395                                |
| --fixtures-per-test             | show fixtures per test           | support  | issue #395                                |
| --pdb,--pdbcls,--trace          | attach debugger to test          | replace  | issue #396                                |
| --capture,--show-capture        | control test output              | replace  | issue #381                                |
| --runxfail                      | make xfail tests fail            | support  | issue #397                                |
| --last-failed,--lfnf            | rerun only the tests that failed | replace  | issue #398                                |
| --failed-first                  | run failed test first            | replace  | issue #380                                |
| --new-first                     | run new tests first              | replace  | issue #399                                |
| --cache-show,--cache-clear      | show cache contents              | replace  | issue #400                                |
| --stepwise,--stepwise-skip      | partitioning                     | ignore   | I think we don't want to support this     |
| --durations                     | show slow tests                  | replace  | issue #381                                |
| --verbose,--quiet,--verbosity   | increase/decrease verbosity      | ignore   | we are swallowing fixture output          |
| --no-header,--no-summary        | disable header / summary         | ignore   | same as above, but see issue #401         |
| --disable-warnings              | disable warnings                 | support  | issue #402                                |
| --showlocals,--no-showlocals    | show/hide locals in tracebacks   | support  | issue #403                                |
| --tb                            | trackback print control          | support  | issue #403                                |
| --full-trace                    | show full traceback              | support  | issue #403                                |
| --color,--code-highlight        | control color output             | replace  | issue #404                                |
| --pastebin                      | send failed tests to pastebin    | ignore   | don't want this feature                   |
| --juint-xml,--junit-prefix      | generate junit-xml style report  | ignore   | don't want this feature                   |
| -w,--pythonwarnings             | set which warnings to report     | support  | issue #402                                |
| --maxfail                       | stop after x number of failures  | replace  | supported via `stop-after`                |
| --strict-config                 | error on config warnings         | support  | issue #402                                |
| --strict-markers                | error on unknown markers         | support  | issue #402                                |
| --config-file                   | load config file from path       | support  | issue #405                                |
| --continue-on-collection-errors | continue after collection fails  | ignore   | don't want this feature                   |
| --rootdir                       | set root-dir for tests           | ignore   | supported with container stuff            |
| --collect-only                  | only collect tests               | ignore   | doesn't make sense                        |
| --pyargs                        | interpret args as python pkgs    | support  | supported via `collect-from-module`       |
| --ignore,--ignore-glob          | ignore path when collecting      | support  | issue #406                                |
| --deselect                      | deselect test during collection  | replace  | supported via DSL                         |
| --confcutdir,--noconftest       | control conftest.py loading      | support  | supported with container stuff            |
| --keep-duplicates               | keep duplicates when collecting  | ignore   | doesn't make sense                        |
| --collect-in-virtualenv         | collect from virtualenv          | support  | issue #406                                |
| --import-mode                   | affect sys.path creation         | ignore   | debugging? fallback on `extra-args`       |
| --doctest-*                     | controls doctests                | support  | issue (pytest doctest support)            |
| --basetemp                      | sets tempdir path                | ignore   | no need with container stuff              |
| --version                       | show version information         | ignore   | no need to somehow report pytest version  |
| --help                          | show help information            | ignore   | no need for this                          |
| -p                              | early-load some plugin           | ignore   | debugging? fallback on `extra-args`       |
| --trace-config                  | trace conftest.py loading        | ignore   | debugging? fallback on just running pytest|
| --debug                         | store trace info in file         | ignore   | don't want this feature                   |
| --override-ini                  | override ini option              | ignore   | debugging? fallback on `extra-args`       |
| --assert                        | control assertion rewriting      | ignore   | debugging? fallback on `extra-args`       |
| --setup-only                    | only set up fixtures             | ignore   | debugging? fallback on `extra-args`       |
| --setup-show                    | show set up of fixtures          | ignore   | debugging? fallback on `extra-args`       |
| --setup-plan                    | show fixtures and tests          | ignore   | debugging? fallback on `extra-args`       |
| --log-level                     | control logging                  | support  | issue #407                                |
| --log-format,--log-date-format  | control logging                  | support  | issue #407                                |
| --log-cli*                      | control logging to console       | ignore   | doesn't make sense                        |
| --log-file*                     | control logging to console       | ignore   | doesn't make sense                        |
| --log-auto-ident                | control logging                  | support  | issue #407                                |
| --log-disable                   | control logging                  | support  | issue #407                                |
