### ISSUE TITLE
Add maelstrom-go-test-specific commented-out lines to default metadata generated by --init.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#325]
**Definition of Done**
- [ ] `CHANGELOG.md` updated.
- [ ] Documentation in `doc/book/head` updated.
- [ ] Issue is in the correct milestone.

**Comment by nfachan** [comment]
It's not clear to me how these would be different than for Rust.

**Comment by bobbobbio** [comment]
I just replaced the Rust specific stuff in the example with something more Go specific.

I dropped the part about environment variables because I couldn't think of any Go example where it would make sense to need it

**Comment by nfachan** [comment]
Looks good.
