### ISSUE TITLE
We should rename the "name" field for images.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#330]
It's not really a name anymore, it's more of a URI or location or something.

**Comment by bobbobbio** [comment]
this is actually called an "image name" in the skopeo docs despite how it looks
https://github.com/containers/skopeo/blob/main/docs/skopeo.1.md#image-names

**Comment by nfachan** [comment]
Yeah, I saw that. I do think URI would be more accurate, but I'm not going to die on that hill.
