### ISSUE TITLE
Look at passing `-o` to `go test -c`.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#357]
You might want to consider using `-o` so that we can control what the binary is named:

> 	-o file
> 	    Compile the test binary to the named file.
> 	    The test still runs (unless -c or -i is specified).
> 	    If file ends in a slash or names an existing directory,
> 	    the test is written to pkg.test in that directory.

**Comment by bobbobbio** [comment]
I already did this, I don't know why I didn't find it originally
