### ISSUE TITLE
Improve `maelstrom-go-test` filter DSL

### ISSUE THREAD

**Issue by bobbobbio** [maelstrom-software/maelstrom#358]
What I'm sorta thinking we would do for selecting packages is have the following selectors
- `package_import_path` the import path for a package, like github.com/foo/bar/baz/v2
- `package_path` the relative path to the package from the module root , likebaz or bin/qux etc , or empty if you want the root package
- `package_name` the name the package declares for itself
And then we would have a special rule with the prefixing so that if you have any prefix of "package" it just defaults to package_import_path. This is means you could still write things like p.eq(...) or package.equals(...)

**Comment by nfachan** [comment]
Oh, interesting proposal.

I definitely think that `package` and its prefixes should match the `package_import_path`. I like your prefix idea. I was trying to figure out different names that didn't start with `package`.

We should be sure we want to use `_`s here. I think the answer is "yes", but we should think about it. I don't know if we have any other `_`s or `-`s in this code.

We may want to get fancy and add another comparator that does go-style pattern matching, but I feel like that would be something we'd add later. (That would match things like `...` or `foo/...`.)

You should run `go help packages` and check it out. It might give you some ideas.

**Comment by bobbobbio** [comment]
> We should be sure we want to use _s here. I think the answer is "yes", but we should think about it. I don't know if we have any other _s or -s in this code.
We chose snake_case for `starts_with` and `ends_with` and also I used snake_case for `node_id` in python
