### ISSUE TITLE
Pytest runner doesn't work

### ISSUE THREAD

**Issue by jscarrott** [maelstrom-software/maelstrom#375]
I thought I would give maelstrom a go. Followed the docs for setting up the pytest runner but it doesn't pick up the pytest dependency. I have a test-requirements.txt with pytest in it but it doesn't seem to be picked up, I tried explicitly adding a layer for it but also no dice.

I see the pytest support is pretty new, so hopefully this is just some documentation I am missing.

**Comment by bobbobbio** [comment]
The test-requirements.txt and layers are about what is available in the test containers, but indeed Maelstrom requires additionally that PyTest be available in the environment in which it is run to list all the tests. Maybe this is what you are running into.

I recommend creating some venv that has PyTest, sourcing that, then running Maelstrom. You can check that this worked by running python3 and trying to import PyTest.

If this is indeed the problem, you are right that we aren't that clear about this in the documentation. We don't mention for other test runners that you need cargo or go installed, but that doesn't seem like a problem. For Python we should make it more clear. For future versions, I've been wondering if we wanted explore changing how this works and instead list the tests inside some test container.

**Comment by jscarrott** [comment]
Oh wait are you saying that the env you are running maelstrom from also needs pytest installed?

Yeah that fixed it and is unexpected from a new user's point of view.

**Comment by bobbobbio** [comment]
Yes that is what I was saying. I'm glad that fixed it.

I want to keep this issue open to mark that we need to fix this gap in the documentation, or create a different issue to do so.

**Comment by bobbobbio** [comment]
this new issue has been make to track the changes to documentation #376
