### ISSUE TITLE
Set up Traction Data Collector

### ISSUE THREAD

**Issue by rosok** [maelstrom-software/maelstrom#384]
Hook up Github API to pull traffic data into a google spreadsheet regularly. (Daily?) 

I want:

- Web traffic (unique visitors) to github page
- Web traffic (unique visitors) to Maelstrom-software.com
- Clones (unique cloners)
- Forks (unique forkers)
- Downloads (unique downloaders) 

All in raw #'s per day.

**Comment by bobbobbio** [comment]
> Web traffic (unique visitors) to Maelstrom-software.com
turns out that github doesn't provide this. it seems that we would have to add our own tracking for this thing

see this discussion about it https://github.com/orgs/community/discussions/31474

**Comment by bobbobbio** [comment]
The spreadsheet was posted in the discord
