### ISSUE TITLE
Test runners should show failed tests before summary.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#391]
**Use Cases**

When I'm running a large batch of tests, it's possible that it takes a while, but also that some of the test fail early on. I want to know that some tests have failed without waiting until the end of the test run.

**Acceptance Criteria**

- [x] There is a window in the test runner TUI that appears and shows failed tests.
- [x] The progress bar should indicate the number of passed versus failed tests. The failed tests don't necessarily have to be a different color, but the counts should indicate there were failures.
- [x] In the simple UI, there should be an indicator that there are failed tests.
- [ ] Optionally, if there are only one or two failures, and if there is room, the first bit of stderr should be included so that I can start fixing it while the tests continue to run.

**Implementation Considerations**

**Definition of Done**
- [x] `CHANGELOG.md` updated.
- [x] Documentation in `doc/book/head` updated.
- [x] Issue is in the correct milestone.

**Comment by bobbobbio** [comment]
>  Optionally, if there are only one or two failures, and if there is room, the first bit of stderr should be included so that I can start fixing it while the tests continue to run.

I think this needs some more thought. The relevant part of the output isn't clear and on my terminal there really isn't enough room to show anything all that useful. We could show it if there is only one failure, but I'm wondering if instead we want to use keyboard controls to let you choose a failure whose output to look at or something along those lines. Something like a collapsible list item
