### ISSUE TITLE
Cannot use maelstrom-pytest on Ubuntu 22.04

### ISSUE THREAD

**Issue by nicolas-slamcore** [maelstrom-software/maelstrom#416]
**Specific Maelstrom Program?**
This happened with maelstrom-pytest (but I have not tested any other)

**Bug Description**
When trying to init, I'm getting an error related to the version of libc:
```
1 ± maelstrom-pytest --init
maelstrom-pytest: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by maelstrom-pytest)
```

**How to Reproduce**
Just run `maelstrom-pytest --init` in a standard, up-to-date, Ubuntu 22.04 environment.

**Expected Behavior**
I'm expecting to be able to use the tool on that OS.

**Additional Context**
The problem is the version of libc.
The latest natively available on this OS is 2.35, but apparently, we need 2.39 to run it.
Since this is a pretty common OS right now, I was expecting compatibility but this may be out of the scope of this project (feel free to close the ticket if that's the case).

**Comment by bobbobbio** [comment]
Hi, thank you for your issue. Yes we do want to make sure our binaries work on Ubuntu 22.04. We are trying generalize them so they don't rely on that specific newer libc version, but something must have gone wrong. Thank you for letting us know.

**Comment by bobbobbio** [comment]
Binaries for the 0.12.0 release have been updated. The new binaries should get past this error you have described.

**Comment by nicolas-slamcore** [comment]
Thanks, I'll give it a try ASAP!

**Comment by bobbobbio** [comment]
let us know how it goes and if you run into any more issues. feel free to reopen this issues if its not fixed or open a new one.

**Comment by nicolas-slamcore** [comment]
So I've managed to pass the init with your latest change, thanks for that!

I'm now experiencing another issue (`failed to compile python`) but I'm not certain if it's related to my environment or not so I'll try to look a bit more into it before opening another one.

**Comment by bobbobbio** [comment]
hmm that's interesting, I'd love to hear more about it. We're actively working on trying to make the experience of `maelstrom-pytest` easier so we've interested in the experience, feel free to stop by our discord and we could help you debug.

**Comment by nicolas-slamcore** [comment]
So about my issue specifically, it was indeed some environmental issue on my end, no need to worry on your side.
I've managed to go a bit further, but the project I am using to test relies on some dependencies (like internal packages, or internal wheel repo) that are normally handled with our pyproject.toml.
Apparently, there is [an issue](https://github.com/maelstrom-software/maelstrom/issues/341) already opened for this so eventually that may be implemented.

I'll keep an eye on it and will certainly try it at some point on a less complex project to wrap my head around it since I like the concept! :)

**Comment by bobbobbio** [comment]
that issue may not be what you are looking for since it is just about using `pyproject.toml` to specify the configuration normally found in `maelstrom-pytest.toml` (not really new functionality just convenience)

I am wondering if you could share some more information about how these dependencies are specified, I'd like to make sure we're tracking some issue to support this scenario if we don't support it already.

**Comment by nicolas-slamcore** [comment]
I am not sure to understand. How do I get maelstrom to use the `pyproject.toml`?

**Comment by nicolas-slamcore** [comment]
Actually, I already have this in my directives:
```
added_layers = [
    # This layer includes all the Python files from our project.
    { glob = "**.{py,pyc,pyi}" },
    # Include pyproject.toml if it exists.
    { glob = "pyproject.toml" },
    # This layer just includes files and directories for mounting the following
    # file-systems and devices.
    { stubs = [ "/{proc,sys,tmp}/", "/dev/{full,null,random,urandom,zero}" ] },
]
```

So I cannot add that line (it tells me it's duplicated). Yet, it fails to install some internal packages `ERROR: Could not find a version that satisfies the requirement ***`).
If I just run `pip install .` in the repo, it works well. Not sure if the issue is on your side or mine tbh!
