### ISSUE TITLE
Provide per-job tracking information

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#64]
Today, the client requests aggregate job state information from the broker. We could instead (or in addition to) have per-job tracking. Clients could request this on a per-job basis. Whenever a job transitioned states, a message would be sent back to the client. If the job transitioned states on the worker, this message would have to get forwarded by the broker.

It's not clear how our existing clients would make use of this, except possibly to implement timeouts (#65). But one could imagine this being useful in some future world.

**Comment by nfachan** [comment]
```
CLIENT AWAITING IMAGES ------------------------------\
     |                                               |
     v                                               |
BROKER AWAITING ARTIFACTS                            |
     |                                               |
     v                                               |
BROKER WAITING TO ASSIGN <-------------\             |
     |                                 |             |
     v                                 |             |
WORKER AWAITING ARTIFACTS + LAYERS ---/|  LOCAL WORKER AWAITING ARTIFACTS + LAYERS
     |                                 |             |
     v                                 |             v
WORKER WAITING TO RUN ----------------/|  LOCAL WORKER WAITING TO RUN
     |                                 |             |
     v                                 |             v
WORKER RUNNING ------------------------/  LOCAL WORKER RUNNING
     |                                               |
     |/---------------------------------------------/
     |
     v
COMPLETE
```

**Comment by bobbobbio** [comment]
There isn't clear criteria in this issue about what done means, but as far as I understand this is complete. I pushed the stream of messages through to the client API, and it seems like it includes what we talked about more or less
